### ISSUE TITLE
User Story: Homepage 

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#1]
Epic: #21 

As a **user** I want to see a homepage so I can see what the website is about and view categories.

**Acceptance Criteria**

**User viewing the home page**

- Given that I am a user
- When I navigate to the website I will see the home page
- Then I will see the home page with a logo, categories, sign in options, header, footer, a hero image and site information text

**Tasks**
- [x] Set up index page and extend the base template
- [x] Add header and footer and hero image
- [x] Add categories and menu items to the nav bar
