### ISSUE TITLE
User story: Stripe Checkout

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#10]
Epic: #26 

As a **user** I want to purchase an item using Stripe.

**Acceptance Criteria**

**User is purchasing an item**

- Given that I am a user
- When I add an item to my cart
- Then I will be able to purchase the item using Stripe.

**Tasks**
- [x] Set up Stripe account
- [x] Add secret and publishable keys to env.py folder and update settings.py with variables
- [x] Follow Stripe documentation and Boutique Ado implementation
- [x] Set workspace to share in order for web hooks to work
