### ISSUE TITLE
User story: Newsletter

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#13]
Epic: #25 

As a **user** I want to sign up to receive a newsletter.

**Acceptance Criteria**

**User wants to sign up for the newsletter**

- Given that I am a user
- When I navigate to the website footer
- Then I will see the option to enter my email address to subscribe to the newsletter

**Tasks**
- [ ] Setup mailchimp account
- [ ] Select form go for the embedded form and copy the code
- [ ] Add to the footer and adjust styling to suit
