### ISSUE TITLE
User story: Adding products

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#14]
Epic: #24 

As a **staff member** I want to be able to add products through the website.

**Acceptance Criteria**

**Staff member wants to add products**

- Given that I am a staff member
- When I navigate to the website and sign in with my staff username/password
- Then I will be able to access the product management area where I can add a product for sale

**Tasks**
- [x] Add template view, urls for add a collectable
- [x] Add url to already to product management button
- [x] Add success and error messages to the view
