### ISSUE TITLE
User story: Edit products

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#15]
Epic: #24 

As a **staff member** I want to be able to edit products through the website.

**Acceptance Criteria**

**Staff member wants to edit products**

- Given that I am a staff member
- When I navigate to the website and sign in with my staff username/password
- Then I will be able to access the product management area where I can edit an existing product

**Tasks**
- [ ] Add edit collectable template, url and view
- [ ] Add edit button to collectable and collectable detail page
- [ ] Add if statement for only admins to be able to see edit button
- [ ] Ass success and error messages to the view
