### ISSUE TITLE
User story: Delete a product

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#16]
Epic: #24 

As a **staff member** I want to be able to delete products through the website.

**Acceptance Criteria**

**Staff member wants to delete products**

- Given that I am a staff member
- When I navigate to the website and sign in with my staff username/password
- Then I will be able to access the product management area where I can delete an existing product.

**Tasks**
- [ ] Add view and url
- [ ] Add delete button to collectable and collectable detail page
- [ ] Add if statement so only admins can see the delete button
