### ISSUE TITLE
User story: Messages

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#17]
As a **user** I want to see a message to confirm my action.

**Acceptance Criteria**

**User has completed an action on the website**

- Given that I am a user
- When I have completed an action on the website
- Then I will see a message validating the action I have taken

**Tasks**
- [x] Add toast templates
- [x] Add message levels using built in django messages
- [x] Add JS script to show toasts
