### ISSUE TITLE
User Story: Item sold out

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#27]
As a **user** once I have purchased a product, it should be marked as sold out and not be available for purchase.

**Acceptance Criteria**

**User has made a successful purchase**

- Given that I am a user
- When I have made a successful purchase of an item
- Then this item will be no longer available for purchase and should be marked as sold out

**Tasks**
- [x] Add product in stock logic to collectable model
- [x] Add logic to decrease the quantity by 1 when an item is sold,
- [x] Disable add to cart button when an item is sold out
