### ISSUE TITLE
User Story: Reviews

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#29]
As a **user** I want to see a form where I can submit a review.

**Acceptance Criteria**

**User viewing the home page**

- Given that I am a user
- When I navigate to the website I will see the home page
- Then I will see an option for reviews

**User clicks on reviews**

- Given that I am a user
- When I click on reviews
- Then I will be redirected to a page where I can fill out a review

**User has submitted a successful review**
- When I have submitted a successful review
- The  i will see it under recent reviews on the page

**Tasks**
- [x] Add a mode', form, view and url l to sell collectable
- [x] Add option to nav bar to select reviews
- [x] Add section for recent reviews and display relevant details
