### ISSUE TITLE
User story: Footer

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#3]
Epic: #21 

As a **user** I want to see a footer containing useful information about the website.

**Acceptance Criteria**

**User viewing the home page**

- Given that I am a user
- When I navigate to the website I will see the home page
- Then I will see a footer containing a privacy policy, contact us, delivery information hyperlinks and social media hyperlinks

**User clicking on footer hyperlinks**

- Given that I am a user
- When I click a hyperlink on in the website footer
- Then I will be redirected to the respective page

**Tasks**
- [x] At footer to the base template
- [x] Add social media links using font awesome and correct rel attributes
- [x] Add link for privacy policy, delivery information and contact us, all links will open in their own respective page
