### ISSUE TITLE
Task: Set up workspace & Install Django

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#4]
Epic: #21 

As a **developer** I want to set up my workspace with Code anywhere and install Django.

**Tasks**
- [x] Create new repository using CI Code anywhere template
- [x] Copy repository to Code anywhere
- [x] Install Django
- [x] Set up main app
