### ISSUE TITLE
User story: 404 pages

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#6]
As a **user** I want to see a 404 page when I have come across a page that is not found.

**Acceptance Criteria**

Given that I am a user
- When I try to access an incorrect URL
- Then I will see a message telling me the page is not available

**Tasks**
- [x] Create a handler function
- [x] Configure the handler in urls
- [x] Add HTML for the page
