### ISSUE TITLE
User story: Product detail page

### ISSUE THREAD

**Issue by Lornavav** [Lornavav/retro-revolution#9]
Epic: #22 

As a **user** when I click on a product I want to see further details of that product.

**Acceptance Criteria**

**User clicks on a single product**

- Given that I am a user
- When I click on a product
- Then I am brought to a new page with the single product displayed.

**User is viewing the single product detail page**

- Given that I have clicked on a product
- When I am viewing the product detail page
- Then I can see the product description, an add to bag button, a keep shopping button, a price, a wishlist button, a category, a genre and a release date

**Tasks**
- [x] from the product model pull fields into a view/template
- [x] Wire up a url
- [x] Display product name, platform, genre, year, description, price,
- [x] Add buttons to add to basket or to return to keep shopping
